const INITIAL_MULTILEVEL_FEEDS = [
  // --- GLOBAL FEED ---
  {
    id: 'feed_global_1',
    level: 'global',
    chapter: 'Global',
    author: 'James Winfield',
    authorHouse: 'Arthur',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    title: 'Interview with Architect M. Gafir: Harmony in Classical Design',
    content: 'The navy is an homage to our naval traditions. It represents power and family overview in modern architecture.',
    category: 'Architecture',
    houseId: 'arthur',
    likes: 48,
    commentsCount: 14,
    rsvpCount: 89,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    location: 'Lisbon, Portugal',
    date: 'AUG 18-20, 2026',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString()
  },
  {
    id: 'feed_global_2',
    level: 'global',
    chapter: 'Global',
    author: 'Lord Percival Vance',
    authorHouse: 'Percival',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    title: 'Weekend in Lisbon: Exclusive Coastal retreat',
    content: 'Our members gathering in Lisbon complete a weekend of private access to heritage estates, fine dining, and coastal sailing.',
    category: 'Travel',
    houseId: 'percival',
    likes: 64,
    commentsCount: 22,
    rsvpCount: 112,
    isRsvped: true,
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    location: 'Lisbon Coast, Portugal',
    date: 'AUG 25, 2026',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString()
  },
  {
    id: 'feed_global_3',
    level: 'global',
    chapter: 'Global',
    author: 'Sir Galahad',
    authorHouse: 'Galahad',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    title: 'Gentleman\'s Wine Tasting - Bordeaux',
    content: 'Private cellar access and masterclass at Château Margaux. Limited allocation reserved for house members.',
    category: 'Lifestyle',
    houseId: 'galahad',
    likes: 78,
    commentsCount: 19,
    rsvpCount: 45,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
    location: 'Château Margaux, France',
    date: 'AUG 12, 2026',
    timestamp: new Date(Date.now() - 3600000 * 12).toISOString()
  },
  {
    id: 'feed_global_4',
    level: 'global',
    chapter: 'Global',
    author: 'Oliver Chen',
    authorHouse: 'Merlin',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    title: 'Sanctuary: The Alpine Spa & Wellness Summit',
    content: 'Quiet sanctuary dedicated to silence. The newly opened wellness pavilion in the Swiss Alps offers a restorative retreat for leaders.',
    category: 'Wellness',
    houseId: 'merlin',
    likes: 92,
    commentsCount: 31,
    rsvpCount: 56,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80',
    location: 'Swiss Alps, Switzerland',
    date: 'SEP 04, 2026',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString()
  },

  // --- COUNTRY FEED (FRANCE CHAPTER) ---
  {
    id: 'feed_country_1',
    level: 'country',
    chapter: 'France Chapter',
    countryCode: 'FR',
    author: 'Henri Dubois',
    authorHouse: 'Tristan',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    title: 'Provence Lavender Trail Walk',
    content: 'Fascinating 4-km morning walk in Burgundy learning from third-generation vignerons. The dedication to heritage legacy is remarkable.',
    category: 'Outdoors',
    houseId: 'tristan',
    likes: 38,
    commentsCount: 9,
    rsvpCount: 28,
    isRsvped: true,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=600&q=80',
    location: 'Valensole, Provence, France',
    date: 'JUL 28-AUG 10, 2026',
    timestamp: new Date(Date.now() - 3600000 * 8).toISOString()
  },
  {
    id: 'feed_country_2',
    level: 'country',
    chapter: 'France Chapter',
    countryCode: 'FR',
    author: 'Sir Lancelot',
    authorHouse: 'Lancelot',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    title: 'Hidden Gems of Lyon: Gastronomic Tour',
    content: 'Explore the secret Traboules of Vieux Lyon with an exclusive private chef guide. Tasting menus at La Mère Brazier.',
    category: 'Gastronomy',
    houseId: 'lancelot',
    likes: 53,
    commentsCount: 15,
    rsvpCount: 34,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
    location: 'Vieux Lyon, France',
    date: 'AUG 22, 2026',
    timestamp: new Date(Date.now() - 3600000 * 18).toISOString()
  },

  // --- CITY FEED (LONDON CHAPTER) ---
  {
    id: 'feed_city_1',
    level: 'city',
    chapter: 'London Chapter',
    city: 'London',
    author: 'Edward Clarke',
    authorHouse: 'Arthur',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    title: 'Private Art Exhibition - Mayfair Gallery',
    content: 'Private evening viewing of modern sculpture at Saatchi & House galleries. Their sense of scale and clarity of purpose matches our House traditions.',
    category: 'Arts and Culture',
    houseId: 'arthur',
    likes: 41,
    commentsCount: 7,
    rsvpCount: 22,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    location: 'Savile Row, London',
    date: 'TONIGHT 7:00 PM',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString()
  },
  {
    id: 'feed_city_2',
    level: 'city',
    chapter: 'London Chapter',
    city: 'London',
    author: 'Lord Percival Vance',
    authorHouse: 'Percival',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    title: 'Best Coffee Spots in Shoreditch',
    content: 'Curated list of quiet, executive-friendly coffee houses in East London ideal for morning strategy sessions.',
    category: 'Lifestyle',
    houseId: 'percival',
    likes: 31,
    commentsCount: 5,
    rsvpCount: 14,
    isRsvped: true,
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
    location: 'Shoreditch, London',
    date: 'EVERY WEEKDAY',
    timestamp: new Date(Date.now() - 3600000 * 14).toISOString()
  },

  // --- TOWN FEED (MAYFAIR CHAPTER) ---
  {
    id: 'feed_town_1',
    level: 'town',
    chapter: 'Mayfair Chapter',
    town: 'Mayfair',
    author: 'William Hart',
    authorHouse: 'Gawain',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    title: 'Cigar & Whisky Evening at The Connaught',
    content: 'An exclusive session with the master sommelier at Connaught Bar. Rare single malts matched with vintage cigars.',
    category: 'Clubs & Membership',
    houseId: 'gawain',
    likes: 57,
    commentsCount: 11,
    rsvpCount: 18,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=600&q=80',
    location: 'The Connaught, Mayfair',
    date: 'AUG 15, 2026',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString()
  },
  {
    id: 'feed_town_2',
    level: 'town',
    chapter: 'Mayfair Chapter',
    town: 'Mayfair',
    author: 'Lord Percival Vance',
    authorHouse: 'Percival',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    title: 'New Morning Ritual in Mayfair',
    content: 'The quietest hours before the city wakes are spent discovering new espresso recipes on Mount Street that understand geometry and perfection.',
    category: 'Lifestyle',
    houseId: 'percival',
    likes: 24,
    commentsCount: 3,
    rsvpCount: 9,
    isRsvped: false,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    location: 'Mount Street, Mayfair',
    date: 'DAILY 7:30 AM',
    timestamp: new Date(Date.now() - 3600000 * 10).toISOString()
  }
];

module.exports = { INITIAL_MULTILEVEL_FEEDS };
